name: Release New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version to release (e.g. 1.2.3)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0


      - name: Merge dev into main
        run: |
          git fetch origin

          git checkout main
          git pull origin main

          git merge origin/dev --no-ff -m "Merge dev into main for v${{ github.event.inputs.version }}"

          git push origin main

      - name: Create tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Pux v${{ github.event.inputs.version }}
          generate_release_notes: true
